import Navbar from '@/components/Navbar'
import GlobalState from '@/context'
import './globals.css'

export const metadata = {
  title: 'eCommerce by Next Js',
  description: 'Generated by ahmed abdelaziz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <Navbar />
          <main>
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  )
}
